export const paths = {
  home: "/",
  landing: "/landing",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  areaCliente: "/area-cliente",
  pdv: "/pdv",
  crm: "/crm",
  gestaoFinanceira: "/gestao-financeira",
  recursosHumanos: "/recursos-humanos",
  estoque: "/estoque",
  planosLavagem: "/planos-lavagem",
  seguranca: "/seguranca",
  history: "/historico",
  profile: "/perfil",
  contactInfo: "/informacoes-contato",
};
